### ISSUE TITLE
i think BHS-Robotics.v5code is broken looks like a merge error

### ISSUE THREAD

**Issue by artemas-radik** [Bronxville-Robotics/Automated-Steering-System#14]
commit cc00c2d39629d05a81fc3e7d2b35b7426f5cc21a on ASS-new

**Comment by ajradik** [comment]
BHS-Robotics.v5code

**Comment by artemas-radik** [comment]
https://github.com/Bronxville-Robotics/Automated-Steering-System/blob/cc00c2d39629d05a81fc3e7d2b35b7426f5cc21a/BHS-Robotics.v5code

**Comment by artemas-radik** [comment]
https://github.com/Bronxville-Robotics/Automated-Steering-System/commits/ASS-new

**Comment by artemas-radik** [comment]
code does not build no matter which code is used from https://github.com/Bronxville-Robotics/Automated-Steering-System/commit/cc00c2d39629d05a81fc3e7d2b35b7426f5cc21a

**Comment by artemas-radik** [comment]
@alexeyGorbunov02 please pull https://github.com/Bronxville-Robotics/Automated-Steering-System/tree/ASS-new and fix

**Comment by artemas-radik** [comment]
resolved by https://github.com/Bronxville-Robotics/Automated-Steering-System/commit/3c2e0785b5d0aa05d51037b7139f3c18d2634e43
